# Generated by Django 5.2.4 on 2026-04-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
