# Generated by Django 5.2.4 on 2026-03-01 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('tiene_vehiculo', models.BooleanField(default=False)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('acompanantes', models.IntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huespedes', to='hotel.hotel')),
            ],
            options={
                'unique_together': {('hotel', 'documento')},
            },
        ),
        migrations.CreateModel(
            name='Acompanante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.CharField(blank=True, max_length=20, null=True)),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_acompanantes', to='huespedes.huesped')),
            ],
            options={
                'verbose_name': 'Acompañante',
                'verbose_name_plural': 'Acompañantes',
            },
        ),
    ]
