# Generated by Django 5.2.4 on 2026-04-04 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('creacion', 'Creación de habitación'), ('mantenimiento', 'Mantenimiento'), ('disponible', 'Habitación disponible'), ('eliminacion', 'Eliminación'), ('reserva', 'Nueva reserva'), ('checkout', 'Check-out'), ('exito', 'Éxito'), ('advertencia', 'Advertencia'), ('error', 'Error'), ('info', 'Información'), ('acceso', 'Acceso de recepcionista')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
